name: GitHub Contributions Snake

on:
  schedule:
    - cron: '18 18 * * *'  # Runs daily at 00:00 IST
  workflow_dispatch:

jobs:
  snake:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Generate Snake animation
        uses: platane/snk@v1.1.0
        with:
          github_user_name: NamanOG
          svg_out_path: 'output/github-contribution-grid-snake.svg'
